# -*- coding:utf-8 -*-
"""
Django settings for ruan project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # 项目根目录
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))  # 配置apps搜索路径
sys.path.insert(0, os.path.join(BASE_DIR, "extra_apps"))  # 配置extra_apps搜索路径


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!  # 安全码
SECRET_KEY = 'dn3*qkc&@mccg^u^-icbdxsh&--wy+fqtzo9ugp3it+q2=btv@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']  # 允许外界访问的地址


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',  # 配置xadmin
    'crispy_forms',  # 配置xadmin所依赖的表单app
    'users',  # 配置用户app
    'courses',  # 配置课程app
    'orgs',  # 配置机构app
    'operation',  # 配置操作app
    'pure_pagination',  # 配置翻页的app
]

AUTH_USER_MODEL = "users.UserProfile"  # 重载默认user

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ruan.urls'  # 指向urls.py的根文件

TEMPLATES = [  # 模板
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',  # 配置媒体文件的url，就是下面的MEDIA_URL
            ],
        },
    },
]

WSGI_APPLICATION = 'ruan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 配置mysql
        'NAME': "ruantong",  # 配置数据库名称
        'USER': 'root',  # 配置mysql用户
        'PASSWORD': "zhangzhiqiang199",  # 配置mysql密码
        'HOST': "127.0.0.1",  # 配置ip地址
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [  # 密码认证
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 配置中文

TIME_ZONE = 'Asia/Shanghai'  # 配置时区

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 改成False可以用本地时间，而不是国际时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# 需要添加的静态文件的配置
STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static"),
# )

# 需要发送邮件的发送人相关信息配置
EMAIL_HOST = "smtp.sina.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "2310091880qq@sina.com"
EMAIL_HOST_PASSWORD = "zhangzhiqiang199"
EMAIL_USE_TLS = False
EMAIL_FROM = "2310091880qq@sina.com"

# 媒体文件路径配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 配置所有静态文件
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
